import json
import os
import importlib.util
from datetime import datetime

from personality import (
    init_personality,
        learn_from_intent,
            analyze_personality
            )

            MEMORY_FILE = "memory.json"
            AGENTS_FILE = "agents.json"
            AGENT_FOLDER = "agents"


            # =============================
            # INIT STORAGE
            # =============================

            def init_storage():

                if not os.path.exists(MEMORY_FILE):
                        json.dump({"usage": {}}, open(MEMORY_FILE, "w"))

                            if not os.path.exists(AGENTS_FILE):
                                    json.dump({}, open(AGENTS_FILE, "w"))

                                        if not os.path.exists(AGENT_FOLDER):
                                                os.mkdir(AGENT_FOLDER)


                                                def load_memory():
                                                    return json.load(open(MEMORY_FILE))


                                                    def save_memory(data):
                                                        json.dump(data, open(MEMORY_FILE, "w"), indent=2)


                                                        def load_agents():
                                                            return json.load(open(AGENTS_FILE))


                                                            def save_agents(data):
                                                                json.dump(data, open(AGENTS_FILE, "w"), indent=2)


                                                                # =============================
                                                                # PRIME AGENT
                                                                # =============================

                                                                class PrimeAgent:

                                                                    def detect_intent(self, text):

                                                                            text = text.lower()

                                                                                    if "research" in text:
                                                                                                return "research"

                                                                                                        if "money" in text:
                                                                                                                    return "finance"

                                                                                                                            if "plan" in text:
                                                                                                                                        return "planning"

                                                                                                                                                if "build" in text or "code" in text:
                                                                                                                                                            return "development"

                                                                                                                                                                    return "general"

                                                                                                                                                                        def log_usage(self, intent):

                                                                                                                                                                                memory = load_memory()

                                                                                                                                                                                        memory["usage"][intent] = \
                                                                                                                                                                                                    memory["usage"].get(intent, 0) + 1

                                                                                                                                                                                                            save_memory(memory)

                                                                                                                                                                                                                def respond(self, intent):
                                                                                                                                                                                                                        return f"🧠 Prime routing → {intent}"


                                                                                                                                                                                                                        # =============================
                                                                                                                                                                                                                        # AGENT FACTORY
                                                                                                                                                                                                                        # =============================

                                                                                                                                                                                                                        class AgentFactory:

                                                                                                                                                                                                                            def create_agent_file(self, intent):

                                                                                                                                                                                                                                    filename = f"{AGENT_FOLDER}/{intent}_agent.py"

                                                                                                                                                                                                                                            if os.path.exists(filename):
                                                                                                                                                                                                                                                        return

                                                                                                                                                                                                                                                                code = f"""
                                                                                                                                                                                                                                                                class {intent.capitalize()}Agent:

                                                                                                                                                                                                                                                                    def run(self, task):
                                                                                                                                                                                                                                                                            print("🤖 {intent.capitalize()} Agent executing:", task)
                                                                                                                                                                                                                                                                            """

                                                                                                                                                                                                                                                                                    open(filename, "w").write(code)

                                                                                                                                                                                                                                                                                            print(f"⚡ CREATED NEW AGENT → {intent}")

                                                                                                                                                                                                                                                                                                def create_if_needed(self):

                                                                                                                                                                                                                                                                                                        memory = load_memory()
                                                                                                                                                                                                                                                                                                                agents = load_agents()

                                                                                                                                                                                                                                                                                                                        for intent, count in memory["usage"].items():

                                                                                                                                                                                                                                                                                                                                    if count >= 3 and intent not in agents:

                                                                                                                                                                                                                                                                                                                                                    agents[intent] = {
                                                                                                                                                                                                                                                                                                                                                                        "created": str(datetime.now())
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                        self.create_agent_file(intent)

                                                                                                                                                                                                                                                                                                                                                                                                                save_agents(agents)


                                                                                                                                                                                                                                                                                                                                                                                                                # =============================
                                                                                                                                                                                                                                                                                                                                                                                                                # AGENT RUNTIME
                                                                                                                                                                                                                                                                                                                                                                                                                # =============================

                                                                                                                                                                                                                                                                                                                                                                                                                class AgentRuntime:

                                                                                                                                                                                                                                                                                                                                                                                                                    def run_agent(self, intent, task):

                                                                                                                                                                                                                                                                                                                                                                                                                            path = f"{AGENT_FOLDER}/{intent}_agent.py"

                                                                                                                                                                                                                                                                                                                                                                                                                                    if not os.path.exists(path):
                                                                                                                                                                                                                                                                                                                                                                                                                                                print("⚠️ No agent yet.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                            return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    spec = importlib.util.spec_from_file_location(intent, path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            module = importlib.util.module_from_spec(spec)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    spec.loader.exec_module(module)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            class_name = f"{intent.capitalize()}Agent"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    agent_class = getattr(module, class_name)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            agent = agent_class()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    agent.run(task)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # =============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # SELF IMPROVEMENT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # =============================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    class SelfImprovement:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def analyze(self):

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                memory = load_memory()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("\n📈 Learning State")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for k, v in memory["usage"].items():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"{k}: {v}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("System adapting...")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # =============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # AGENTOS CORE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # =============================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    class AgentOS:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def __init__(self):

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                init_storage()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        init_personality()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.prime = PrimeAgent()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.factory = AgentFactory()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.runtime = AgentRuntime()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.improve = SelfImprovement()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("🚀 AgentOS ONLINE")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def run(self):

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            while True:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        user = input("\nYou: ")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if user == "exit":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                intent = self.prime.detect_intent(user)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.prime.log_usage(intent)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        learn_from_intent(intent)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(self.prime.respond(intent))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.factory.create_if_needed()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.runtime.run_agent(intent, user)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.improve.analyze()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    analyze_personality()


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # =============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # START
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # =============================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        AgentOS().run()